version: '3.7'
services:
  app:
    image: jekyll/jekyll:pages
    command:
    # 追加プラグインのインストールをする
      - "bash"
      - "-c"
      - "gem install jekyll-include-cache webrick && jekyll serve --force_polling"
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000